/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useControls } from "leva";
import React, { useEffect, useRef } from "react";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";

export function Avatar(props) {
  const { animation } = props;
  const { headFollow, cursorFollow, wireframe } = useControls({
    headFollow: false,
    cursorFollow: false,
    wireframe: false,
  });
  const group = useRef();
  const currentAnimation = useRef();
  const { scene, materials } = useGLTF("models/model.glb");
  const avatar = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);

  const { animations: typingAnimation } = useFBX("animations/Typing.fbx");
  const { animations: standingAnimation } = useFBX(
    "animations/StandingIdle.fbx"
  );
  const { animations: fallingAnimation } = useFBX("animations/FallingIdle.fbx");
  const { animations: macarenaAnimation } = useFBX(
    "animations/MacarenaDance.fbx"
  );
  const { animations: pointingAnimation } = useFBX(
    "animations/PointingGesture.fbx",
  );
  const { animations: wavingAnimation } = useFBX(
    "animations/WavingGesture.fbx",
  );
  const { animations: gangnamStyleAnimation } = useFBX(
    "animations/GangnamStyle.fbx",
  );

  typingAnimation[0].name = "Typing";
  standingAnimation[0].name = "Standing";
  fallingAnimation[0].name = "Falling";
  macarenaAnimation[0].name = "Macarena";
  pointingAnimation[0].name = "Pointing";
  wavingAnimation[0].name = "Waving";
  gangnamStyleAnimation[0].name = "GangnamStyle";

  const { actions } = useAnimations(
    [
      typingAnimation[0],
      standingAnimation[0],
      fallingAnimation[0],
      macarenaAnimation[0],
      pointingAnimation[0],
      wavingAnimation[0],
      gangnamStyleAnimation[0],
    ],
    group,
  );

  useFrame((state) => {
    if (headFollow) {
      group.current?.getObjectByName("Head")?.lookAt(state.camera.position);
    }
    if (cursorFollow) {
      const target = new THREE.Vector3(state.mouse.x, state.mouse.y, 1);
      group.current?.getObjectByName("Spine2")?.lookAt(target);
    }
  });

  useEffect(() => {
    if (currentAnimation.current === animation) {
      return;
    }

    const action = actions[animation];

    if (!action) {
      return;
    }

    currentAnimation.current = animation;
    action.reset().fadeIn(0.5).play();

    return () => {
      action.reset().fadeOut(0.5);
    };
  }, [animation]);

  useEffect(() => {
    Object.values(materials || {}).forEach((material) => {
      material.wireframe = wireframe;
    });
  }, [materials, wireframe]);

  return (
    <group {...props} ref={group} dispose={null}>
      <group rotation-y={Math.PI}>
        <primitive object={avatar} />
      </group>
    </group>
  );
}

useGLTF.preload("models/model.glb");
